export function generatePubspec(projectName, state, feats) {
  const deps = {}
  const devDeps = {}

  // flutter
  deps['flutter'] = { sdk: 'flutter' }

  // state management
  if (state === 'bloc')     { deps['flutter_bloc'] = '^8.1.0'; deps['equatable'] = '^2.0.5' }
  if (state === 'riverpod') { deps['flutter_riverpod'] = '^2.4.0'; deps['riverpod_annotation'] = '^2.3.0' }
  if (state === 'provider') { deps['provider'] = '^6.1.0' }
  if (state === 'getx')     { deps['get'] = '^4.6.6' }

  // DI (not getx)
  if (state !== 'getx') {
    deps['get_it'] = '^7.6.0'
    deps['injectable'] = '^2.3.0'
    devDeps['injectable_generator'] = '^2.4.0'
  }

  // dartz for functional error handling (clean arch / bloc)
  if (state === 'bloc' || state === 'riverpod' || state === 'provider') {
    deps['dartz'] = '^0.10.1'
  }

  // features
  if (feats.includes('api')) {
    deps['dio'] = '^5.4.0'
    deps['retrofit'] = '^4.0.0'
    deps['json_annotation'] = '^4.8.1'
    devDeps['retrofit_generator'] = '^8.0.0'
    devDeps['json_serializable'] = '^6.7.0'
    if (!feats.includes('codegen')) {
      devDeps['build_runner'] = '^2.4.0'
    }
  }
  if (feats.includes('storage')) {
    deps['hive_flutter'] = '^1.1.0'
    deps['hive'] = '^2.2.3'
    devDeps['hive_generator'] = '^2.0.1'
  }
  if (feats.includes('router'))   deps['go_router'] = '^13.0.0'
  if (feats.includes('theme'))    deps['flex_color_scheme'] = '^7.3.1'
  if (feats.includes('env'))      deps['flutter_dotenv'] = '^5.1.0'
  if (feats.includes('push') || feats.includes('firebase')) {
    deps['firebase_core'] = '^2.24.0'
  }
  if (feats.includes('push')) {
    deps['firebase_messaging'] = '^14.7.0'
    deps['flutter_local_notifications'] = '^16.3.0'
  }
  if (feats.includes('firebase')) {
    deps['cloud_firestore'] = '^4.14.0'
    deps['firebase_auth'] = '^4.16.0'
  }

  if (feats.includes('codegen')) {
    deps['freezed_annotation'] = '^2.4.1'
    deps['json_annotation'] = '^4.8.1'
    devDeps['freezed'] = '^2.4.1'
    devDeps['json_serializable'] = '^6.7.0'
    devDeps['build_runner'] = '^2.4.0'
  }

  // dev deps base
  devDeps['flutter_test'] = { sdk: 'flutter' }
  if (feats.includes('lints')) {
    devDeps['flutter_lints'] = '^3.0.0'
  }
  if (!devDeps['build_runner'] && (state === 'riverpod' || feats.includes('api') || feats.includes('storage') || feats.includes('codegen'))) {
     devDeps['build_runner'] = '^2.4.0'
  }
  devDeps['mocktail'] = '^1.0.0'

  if (state === 'riverpod') {
    devDeps['riverpod_generator'] = '^2.3.0'
    devDeps['custom_lint'] = '^0.5.0'
    devDeps['riverpod_lint'] = '^2.3.0'
  }

  const fmtDep = (obj) =>
    Object.entries(obj).map(([k, v]) =>
      typeof v === 'object'
        ? `  ${k}:\n    sdk: ${v.sdk}`
        : `  ${k}: ${v}`
    ).join('\n')

  return `name: ${projectName}
description: Generated by Flutter Arch Studio
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
${fmtDep(deps)}

dev_dependencies:
${fmtDep(devDeps)}

flutter:
  uses-material-design: true
${feats.includes('l10n') ? '  generate: true' : ''}
`
}
